FROM folioci/openjdk8-jre:latest

# Set the location of the verticles
ENV VERTICLE_HOME /usr/verticles

# Copy your fat jar to the container
COPY target/$VERTICLE_FILE $VERTICLE_HOME/${VERTICLE_FILE}

# Expose this port for the app locally in the container.
EXPOSE 8081
